// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PerfectFit.Infrastructure.Data;

#nullable disable

namespace PerfectFit.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110193302_AddChallengeGoalType")]
    partial class AddChallengeGoalType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PerfectFit.Core.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsSecret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_secret");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RewardCosmeticCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reward_cosmetic_code");

                    b.Property<int>("RewardType")
                        .HasColumnType("integer")
                        .HasColumnName("reward_type");

                    b.Property<int>("RewardValue")
                        .HasColumnType("integer")
                        .HasColumnName("reward_value");

                    b.Property<string>("UnlockCondition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("unlock_condition");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_achievements_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_achievements_name");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_user_id");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer")
                        .HasColumnName("target_user_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_admin_audit_logs_action");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_admin_audit_logs_admin_user_id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_admin_audit_logs_timestamp");

                    b.ToTable("admin_audit_logs", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChallengeTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("challenge_template_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int?>("GoalType")
                        .HasColumnType("integer")
                        .HasColumnName("goal_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer")
                        .HasColumnName("target_value");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("XPReward")
                        .HasColumnType("integer")
                        .HasColumnName("xp_reward");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_challenges_type");

                    b.HasIndex("ChallengeTemplateId", "StartDate")
                        .IsUnique()
                        .HasDatabaseName("ix_challenges_template_start_date")
                        .HasFilter("challenge_template_id IS NOT NULL");

                    b.HasIndex("IsActive", "StartDate", "EndDate")
                        .HasDatabaseName("ix_challenges_active_dates");

                    b.ToTable("challenges", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.ChallengeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("GoalType")
                        .HasColumnType("integer")
                        .HasColumnName("goal_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer")
                        .HasColumnName("target_value");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("XPReward")
                        .HasColumnType("integer")
                        .HasColumnName("xp_reward");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_challenge_templates_is_active");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_challenge_templates_type");

                    b.HasIndex("Type", "IsActive")
                        .HasDatabaseName("ix_challenge_templates_type_is_active");

                    b.ToTable("challenge_templates", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.ClaimedSeasonReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<int>("SeasonRewardId")
                        .HasColumnType("integer")
                        .HasColumnName("season_reward_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SeasonRewardId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_claimed_season_rewards_user");

                    b.HasIndex("UserId", "SeasonRewardId")
                        .IsUnique()
                        .HasDatabaseName("ix_claimed_season_rewards_user_reward");

                    b.ToTable("claimed_season_rewards", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.Cosmetic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("asset_url");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("preview_url");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cosmetics_code");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("ix_cosmetics_is_default");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cosmetics_name");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_cosmetics_type");

                    b.ToTable("cosmetics", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BoardState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("board_state");

                    b.Property<string>("ClientFingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Combo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("combo");

                    b.Property<string>("CurrentPieces")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("current_pieces");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTime?>("LastMoveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LinesCleared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("lines_cleared");

                    b.Property<int>("MaxCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_combo");

                    b.Property<int>("MoveCount")
                        .HasColumnType("integer");

                    b.Property<string>("MoveHistory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PieceBagState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("piece_bag_state");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("score");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_game_sessions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_game_sessions_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_game_sessions_user_id_status");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.LeaderboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_session_id");

                    b.Property<int>("LinesCleared")
                        .HasColumnType("integer")
                        .HasColumnName("lines_cleared");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer")
                        .HasColumnName("max_combo");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_leaderboard_entries_game_session_id_unique");

                    b.HasIndex("Score")
                        .IsDescending()
                        .HasDatabaseName("ix_leaderboard_entries_score");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_leaderboard_entries_user_id");

                    b.HasIndex("UserId", "Score")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_leaderboard_entries_user_id_score");

                    b.ToTable("leaderboard_entries", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.PersonalGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_value");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer")
                        .HasColumnName("target_value");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_personal_goals_user");

                    b.HasIndex("UserId", "IsCompleted")
                        .HasDatabaseName("ix_personal_goals_user_completed");

                    b.ToTable("personal_goals", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("theme");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_seasons_active");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_number");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.SeasonArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<int>("FinalTier")
                        .HasColumnType("integer")
                        .HasColumnName("final_tier");

                    b.Property<int>("FinalXP")
                        .HasColumnType("integer")
                        .HasColumnName("final_xp");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_season_archives_user_season_unique");

                    b.ToTable("season_archives", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.SeasonReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RewardType")
                        .HasColumnType("integer")
                        .HasColumnName("reward_type");

                    b.Property<int>("RewardValue")
                        .HasColumnType("integer")
                        .HasColumnName("reward_value");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<int>("XPRequired")
                        .HasColumnType("integer")
                        .HasColumnName("xp_required");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "Tier")
                        .IsUnique()
                        .HasDatabaseName("ix_season_rewards_season_tier");

                    b.ToTable("season_rewards", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentSeasonTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_season_tier");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_streak");

                    b.Property<int>("CurrentWinStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_win_streak");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email_verification_token");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_token_expiry");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<int?>("EquippedAvatarFrameId")
                        .HasColumnType("integer")
                        .HasColumnName("equipped_avatar_frame_id");

                    b.Property<int?>("EquippedBadgeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipped_badge_id");

                    b.Property<int?>("EquippedBoardThemeId")
                        .HasColumnType("integer")
                        .HasColumnName("equipped_board_theme_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_attempts");

                    b.Property<int>("FastGames")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("fast_games");

                    b.Property<int>("GamesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("games_played");

                    b.Property<int>("HighAccuracyGames")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("high_accuracy_games");

                    b.Property<int>("HighScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("high_score");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastDisplayNameChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_display_name_change_at");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastPlayedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_date");

                    b.Property<DateTime?>("LastStreakNotificationSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_streak_notification_sent_at");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("longest_streak");

                    b.Property<int>("NightGames")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("night_games");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PerfectGames")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("perfect_games");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("SeasonPassXP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("season_pass_xp");

                    b.Property<int>("StreakFreezeTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("streak_freeze_tokens");

                    b.Property<string>("Timezone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<int>("TotalWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_wins");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_display_name");

                    b.HasIndex("HighScore")
                        .IsDescending()
                        .HasDatabaseName("ix_users_high_score");

                    b.HasIndex("ExternalId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_id_provider");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer")
                        .HasColumnName("achievement_id");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_achievements_user_achievement");

                    b.HasIndex("UserId", "UnlockedAt")
                        .HasDatabaseName("ix_user_achievements_user_unlocked");

                    b.ToTable("user_achievements", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.UserChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer")
                        .HasColumnName("challenge_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_progress");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId", "ChallengeId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_challenges_user_challenge");

                    b.HasIndex("UserId", "IsCompleted")
                        .HasDatabaseName("ix_user_challenges_user_completed");

                    b.ToTable("user_challenges", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.UserCosmetic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CosmeticId")
                        .HasColumnType("integer")
                        .HasColumnName("cosmetic_id");

                    b.Property<DateTime>("ObtainedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("obtained_at");

                    b.Property<int>("ObtainedFrom")
                        .HasColumnType("integer")
                        .HasColumnName("obtained_from");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CosmeticId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_cosmetics_user");

                    b.HasIndex("UserId", "CosmeticId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_cosmetics_user_cosmetic");

                    b.ToTable("user_cosmetics", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.ClaimedSeasonReward", b =>
                {
                    b.HasOne("PerfectFit.Core.Entities.SeasonReward", "SeasonReward")
                        .WithMany()
                        .HasForeignKey("SeasonRewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectFit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeasonReward");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.GameSession", b =>
                {
                    b.HasOne("PerfectFit.Core.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.LeaderboardEntry", b =>
                {
                    b.HasOne("PerfectFit.Core.Entities.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectFit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.PersonalGoal", b =>
                {
                    b.HasOne("PerfectFit.Core.Entities.User", "User")
                        .WithMany("PersonalGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.SeasonArchive", b =>
                {
                    b.HasOne("PerfectFit.Core.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectFit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.SeasonReward", b =>
                {
                    b.HasOne("PerfectFit.Core.Entities.Season", "Season")
                        .WithMany("Rewards")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.UserAchievement", b =>
                {
                    b.HasOne("PerfectFit.Core.Entities.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectFit.Core.Entities.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.UserChallenge", b =>
                {
                    b.HasOne("PerfectFit.Core.Entities.Challenge", "Challenge")
                        .WithMany("UserChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectFit.Core.Entities.User", "User")
                        .WithMany("UserChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.UserCosmetic", b =>
                {
                    b.HasOne("PerfectFit.Core.Entities.Cosmetic", "Cosmetic")
                        .WithMany("UserCosmetics")
                        .HasForeignKey("CosmeticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectFit.Core.Entities.User", "User")
                        .WithMany("UserCosmetics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cosmetic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.Challenge", b =>
                {
                    b.Navigation("UserChallenges");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.Cosmetic", b =>
                {
                    b.Navigation("UserCosmetics");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.Season", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.User", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("PersonalGoals");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserChallenges");

                    b.Navigation("UserCosmetics");
                });
#pragma warning restore 612, 618
        }
    }
}
