// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerfectFit.Infrastructure.Data;

#nullable disable

namespace PerfectFit.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103022205_ChangeAuditLogUserIdsToInt")]
    partial class ChangeAuditLogUserIdsToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("PerfectFit.Core.Entities.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("admin_user_id");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_user_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_admin_audit_logs_action");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_admin_audit_logs_admin_user_id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_admin_audit_logs_timestamp");

                    b.ToTable("admin_audit_logs", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BoardState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("board_state");

                    b.Property<string>("ClientFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Combo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("combo");

                    b.Property<string>("CurrentPieces")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("current_pieces");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTime?>("LastMoveAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LinesCleared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("lines_cleared");

                    b.Property<int>("MaxCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("max_combo");

                    b.Property<int>("MoveCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoveHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PieceBagState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("piece_bag_state");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("score");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_game_sessions_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_game_sessions_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_game_sessions_user_id_status");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.LeaderboardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("achieved_at");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("game_session_id");

                    b.Property<int>("LinesCleared")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lines_cleared");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_combo");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_leaderboard_entries_game_session_id_unique");

                    b.HasIndex("Score")
                        .IsDescending()
                        .HasDatabaseName("ix_leaderboard_entries_score");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_leaderboard_entries_user_id");

                    b.HasIndex("UserId", "Score")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_leaderboard_entries_user_id_score");

                    b.ToTable("leaderboard_entries", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<int>("GamesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("games_played");

                    b.Property<int>("HighScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("high_score");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastUsernameChangeAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_username_change_at");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("HighScore")
                        .IsDescending()
                        .HasDatabaseName("ix_users_high_score");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.HasIndex("ExternalId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_id_provider");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.GameSession", b =>
                {
                    b.HasOne("PerfectFit.Core.Entities.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.LeaderboardEntry", b =>
                {
                    b.HasOne("PerfectFit.Core.Entities.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectFit.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectFit.Core.Entities.User", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
